# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'AI Research Engineer'
    org_name: 'Flavio Pinzarrone'
    description: "I'm an AI Research Engineer with a particular interest in autonomous systems and robotics. My research focuses mainly on applying machine learning solutions for onboard perception, control, and state estimation in autonomous robots. Currently collaborating with the TII Drone Racing Team, achieving 2nd place in the AI Grand Challenge and 1st place in the AI Multi-Drone Challenge at A2RL."
    keywords: 'Flavio Pinzarrone, AI Research Engineer, autonomous robotics, drone racing, machine learning, computer vision, PhD robotics, autonomous systems, optimal control, deep learning, artificial intelligence'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Flavio Pinzarrone"

# Site footer
footer:
  copyright:
    notice: '© 2025 Flavio Pinzarrone. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
